#!/usr/bin/env python

# written by Adam Lopez

import optparse
import sys
import bleu

optparser = optparse.OptionParser()
optparser.add_option("-r", "--reference", dest="reference", default="../data/train.ref", help="Target language reference sentences")
(opts,_) = optparser.parse_args()

ref = [line.strip().split() for line in open(opts.reference)]
hyp = [line.strip().split() for line in sys.stdin]

stats = [0 for i in xrange(10)]
for (r,h) in zip(ref, hyp):
  stats = [sum(scores) for scores in zip(stats, bleu.bleu_stats(h,r))]
print bleu.bleu(stats)

